// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUDTDHE1m6MCdewnisPzHKNh2Xh7JGgGA',
    appId: '1:347627455314:web:7152ed55358cd9d5f8308b',
    messagingSenderId: '347627455314',
    projectId: 'latihan-email-verificati-25627',
    authDomain: 'latihan-email-verificati-25627.firebaseapp.com',
    storageBucket: 'latihan-email-verificati-25627.appspot.com',
    measurementId: 'G-NQ90SSVWYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPn4QCC1kUAd_J_Bym_ZVlN6LKPCjpH8M',
    appId: '1:347627455314:android:efb1b3a32ff7babdf8308b',
    messagingSenderId: '347627455314',
    projectId: 'latihan-email-verificati-25627',
    storageBucket: 'latihan-email-verificati-25627.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNZP3IU0qsf4HaicRd-pSN30QY_f4Pun4',
    appId: '1:347627455314:ios:1be07c8d9966ca36f8308b',
    messagingSenderId: '347627455314',
    projectId: 'latihan-email-verificati-25627',
    storageBucket: 'latihan-email-verificati-25627.appspot.com',
    iosBundleId: 'com.example.quranMasApry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNZP3IU0qsf4HaicRd-pSN30QY_f4Pun4',
    appId: '1:347627455314:ios:d9891000f12d8d09f8308b',
    messagingSenderId: '347627455314',
    projectId: 'latihan-email-verificati-25627',
    storageBucket: 'latihan-email-verificati-25627.appspot.com',
    iosBundleId: 'com.example.quranMasApry.RunnerTests',
  );
}
